name: PS5 Tracker Backup

on:
  schedule:
    - cron: "1-59/5 * * * *"
  workflow_dispatch:

jobs:
  run-tracker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm install

      - run: node ps5-bot.js
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
